---
####################################################
#          ModuleBuilder Configuration             #
####################################################

SourcePath: source
CopyPaths: []
Prefix: prefix.ps1
Suffix: suffix.ps1
Encoding: UTF8
VersionedOutputDirectory: true

####################################################
#              Pipeline Configuration              #
####################################################

BuildWorkflow:
  '.':
    - build
    - test

  build:
    - Clean
    - Build_ModuleOutput_ModuleBuilder
    - Create_changelog_release_output

  pack:
    - build
    - package_module_nupkg

  test:
    - build
    - Pester_Tests_Stop_On_Fail
    - Pester_if_Code_Coverage_Under_Threshold

  # Note: 'analyze' task is handled directly in build.ps1

  publish:
    - publish_module_to_gallery

  docs:
    - Build_Module_ModuleBuilder
    - Update_markdown_help_source
    - Generate_MAML_from_markdown_help_source

####################################################
#       Sampler Pipeline Configuration             #
####################################################

Sampler:
  DefaultOutputDirectory: 'output'

ModuleBuildTasks:
  Sampler:
    - '*.build.Sampler.ib.tasks'
  Sampler.GitHubTasks:
    - '*.ib.tasks'
  ModuleBuilder:
    - '*.build.ModuleBuilder.ib.tasks'

TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

####################################################
#       PESTER Configuration                       #
####################################################

Pester:
  # Script key triggers Pester task detection
  Script:
    - tests/Unit/Module.Tests.ps1
  ExcludeTag:
    - helpQuality
    - Integration
  Tag:
  OutputFile: output/testResults/testResults.xml
  OutputFormat: NUnitXml
  PassThru: true

####################################################
#           Module Manifest Properties             #
####################################################

####################################################
#       PlatyPS / Documentation Configuration      #
####################################################

# Help source folder containing markdown docs (relative to project root)
HelpSourceFolder: docs

# Culture/locale for help files
HelpCultureInfo: en-US

# Copy generated MAML to built module folder
CopyHelpMamlToBuiltModuleBase: true

####################################################
#       PSScriptAnalyzer Configuration            #
####################################################

PSScriptAnalyzer:
  Script: source
  Settings: PSScriptAnalyzerSettings.psd1
  ExcludeRule:
  IncludeRule:

ChangelogConfig:
  UpdateChangelogOnPrerelease: false
  FilterByPath:
    - source/

GitHubConfig:
  GitHubFilesToAdd:
    - 'CHANGELOG.md'
  GitHubConfigUserName: christaylorcodes
  GitHubConfigUserEmail: chris@yourconnectedtech.com
  UpdateChangelogOnPrerelease: false
